export const ACHIEVEMENTS = [
  {
    title: "Aruswap",
    place: "2nd",
    event: "ETHGlobal",
    year: "2024",
    track: "Cow Swap Hooks",
    description: "Cross-chain swap leveraging CCTP.",
    link: "https://ethglobal.com/showcase/aruswap-ebpfr",
    type: "silver",
    projectLogo: "/achievements-logos/Aruswap-logo.png",
    compLogo: "/competition-logos/EthGlobal.svg",
  },
  {
    title: "PopUp Pass",
    place: "3rd",
    event: "Edge City Lanna",
    year: "2024",
    track: "World ID",
    description: "On-chain identity verification with token-bound accounts.",
    link: "https://dorahacks.io/buidl/18507",
    type: "bronze",
    projectLogo: "/achievements-logos/PopUpPass-logo.webp",
    compLogo: "/competition-logos/EdgeCityLanna.svg",
  },
  {
    title: "Meme Arena",
    place: "2nd",
    event: "Aleph Hackathon",
    year: "2024",
    track: "Solana Track",
    description: "Web3 game featuring memecoins with Pokémon-style battles.",
    link: "https://dorahacks.io/buidl/15201/",
    type: "silver",
    projectLogo: "/achievements-logos/MemeArena-logo.webp",
    compLogo: "/competition-logos/Aleph.webp",
  },
  {
    title: "Enigma Vote",
    place: "3rd",
    event: "Ethereum Argentina",
    year: "2024",
    track: "Zero Knowledge Track",
    description: "Decentralized anonymous voting platform.",
    link: "https://taikai.network/ethargentina/hackathons/level-up-argentina-2024/projects/clzelhbkt07j0wx01vjcgcsi9/idea",
    type: "bronze",
    projectLogo: "/achievements-logos/EnigmaVote-logo.svg",
    compLogo: "/competition-logos/TheLevelUp.jpg",
  },
  {
    title: "Gardens",
    place: "1st",
    event: "Allo on Arbitrum",
    year: "2024",
    track: "Noble Funding",
    description:
      "Funding distribution platform and governance framework featuring Conviction Voting.",
    link: "https://app.buidlbox.io/projects/convictio?path=projects%2Fconvictio",
    type: "gold",
    projectLogo: "/achievements-logos/Gardens-logo.webp",
    compLogo: "/competition-logos/AlloOnArbitrum.png",
  },
  {
    title: "Veritrust",
    place: "1st",
    event: "Ethereum Argentina",
    year: "2023",
    track: "Public Goods Track",
    description:
      "Blockchain platform ensuring transparency and efficiency in public tenders.",
    link: "https://taikai.network/ethargentina/hackathons/buildathon-2023/projects/clkwmn1ka00nqt401wio2a8pe/idea",
    type: "gold",
    projectLogo: "/achievements-logos/VeriTrust-logo.png",
    compLogo: "/competition-logos/EthArgentina.png",
  },
];

export const PROJECTS = [
  {
    id: "gardens",
    title: "Gardens",
    description:
      "Decentralized funding allocation platform with innovative governance mechanisms powered by Conviction Voting.",
    imageUri: "/project-images/gardens.png",
    url: "https://www.gardens.fund/",
    tags: ["Web3", "DeFi", "DAO", "Smart Contracts", "Next.js"],
    techsUsed: ["Next.js", "Typescript", "TailwindCss", "Viem", "Wagmi"],
  },
  {
    id: "el-eco",
    title: "El Eco",
    description:
      "Modern news media platform featuring real-time updates, responsive design, and seamless content and ads management integration.",
    imageUri: "/project-images/el-eco.png",
    url: "https://www.eleco.com.ar/",
    tags: ["Next.js", "CMS", "Media", "SEO", "Performance"],
    techsUsed: ["Next.js", "Javascript", "Sass"],
  },
  {
    id: "artic",
    title: "Artic",
    description:
      "Advanced content management system designed specifically for news organizations, optimizing editorial workflow and publishing.",
    imageUri: "/project-images/artic.png",
    url: "https://artic.ar/",
    tags: ["CMS", "TypeScript", "API", "Editorial", "Dashboard"],
    techsUsed: ["React.js", "Bootstrap", "JavaScript"],
  },
  {
    id: "growpro",
    title: "GrowPro",
    description:
      "E-commerce platform for international education experiences, featuring personalized journey planning and booking system.",
    imageUri: "/project-images/growpro.png",
    url: "https://growproexperience.com/",
    tags: ["E-commerce", "Next.js", "International", "Education", "UX"],
    techsUsed: ["Next.js", "JavaScript", "Sass"],
  },
  // {
  //   id: "equilibra",
  //   title: "Equilibra",
  //   description:
  //     "Web3 crowdfunding platform enabling transparent and decentralized fundraising within Ethereum network.",
  //   imageUri: "/project-images/equilibra.png",
  //   url: "https://equilibra-front.vercel.app/",
  //   tags: ["Web3", "Crowdfunding", "DeFi", "React", "Blockchain"],
  // },
];
